FROM node:18-alpine as builder
ARG NODE_ENV=production
ARG ENV_PATH=/env/.env
WORKDIR /app
COPY ./package.* ./yarn.* ./
RUN yarn install
COPY . .
RUN yarn build

FROM node:18-alpine
ARG NODE_ENV=production
ARG ENV_PATH=/env/.env
WORKDIR /app

COPY --from=builder /app/package.* /app/yarn.* ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY public ./public


ENV PORT=3000
ENV ENV_PATH=/env/.env

CMD [ "yarn", "start", "echo ${ENV_PATH}" ]



